#!/usr/bin/env bash
# Behavioral regressions for ask-user authority instructions generated by fm-brief.
#
# Ship briefs no longer carry ask-user wording. That wording existed to route
# no-mistakes pipeline ask-user findings back to firstmate, and a ship brief now
# carries only its work item and the commit/push/PR close-out. The secondmate
# charter still reaches the authority boundary through its home's tracked
# AGENTS.md, which is what this file now pins.
set -u

# shellcheck source=tests/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"



