#!/usr/bin/env bash
# Behavioral regressions for ask-user authority instructions generated by fm-brief.
#
# Ship briefs no longer carry ask-user wording. That wording existed to route
# no-mistakes pipeline ask-user findings back to firstmate, and a ship brief now
# carries only its work item and the commit/push/PR close-out. The secondmate
# charter still reaches the authority boundary through its home's tracked
# AGENTS.md, which is what this file now pins.
set -u

# shellcheck source=tests/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

BRIEF="$ROOT/bin/fm-brief.sh"
TMP_ROOT=$(fm_test_tmproot fm-ask-user-authority)

test_secondmate_instruction_generation() {
  local home charter
  home="$TMP_ROOT/home"
  mkdir -p "$home/data"

  FM_HOME="$home" FM_ROOT_OVERRIDE="$ROOT" FM_SECONDMATE_CHARTER='Handle sample work.' \
    "$BRIEF" authority-mate --secondmate --no-projects >/dev/null 2>&1
  charter="$home/data/authority-mate/brief.md"
  # shellcheck disable=SC2016 # Backticks are literal generated Markdown.
  assert_grep 'The local `AGENTS.md` is your job description' "$charter" \
    "generated secondmate charter does not load the tracked authority boundary"
  assert_no_grep 'continuous frame-by-frame monitoring' "$charter" \
    "generated secondmate charter duplicated the detailed authority procedure"
  pass "secondmates receive the authority rule through generated instructions"
}

test_secondmate_instruction_generation
